---
# defaults file for kubeadm-k8s
docker_version_under_1_17: "5:18.09.9~3-0~debian-buster"
docker_version_1_17_and_over: "5:19.03.5~3-0~debian-buster"
kubeadm_version: "1.18.0-00"

k8s_version: "1.18.0"
k8s_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"

k8s_service_cidr: "192.144.0.0/12"
k8s_pod_network_cidr: "192.168.0.0/16"

k8s_worker_group: "{{ groups['k8s-worker'] }}"
k8s_primary_controlplane: "{{ groups['k8s-control'][0] }}"
k8s_controlplane_group: "{{ groups['k8s-control'] }}"
